- https://github.com/arlk/ConvexBodyProximityQueries.jl

In [1]:
using Revise, GeometryTypes, LazySets, BenchmarkTools
using StaticArrays

┌ Info: Recompiling stale cache file /home/mforets/.julia/compiled/v1.2/Revise/M1Qoh.ji for Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
└ @ Base loading.jl:1240
┌ Info: Recompiling stale cache file /home/mforets/.julia/compiled/v1.2/LazySets/NjrGc.ji for LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043]
└ @ Base loading.jl:1240
ERROR: LoadError: LoadError: syntax: extra token "GeometryTypes" after end of expression
Stacktrace:
 [1] top-level scope at /home/mforets/.julia/dev/LazySets/src/convert.jl:918
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1094
 [4] include at ./Base.jl:31 [inlined]
 [5] include(::String) at /home/mforets/.julia/dev/LazySets/src/LazySets.jl:4
 [6] top-level scope at /home/mforets/.julia/dev/LazySets/src/LazySets.jl:119
 [7] include at ./boot.jl:328 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1094
 [9] include(::Module, ::String) at ./Base.jl:31
 [10] top-level scope at none:2
 [11] eval

ErrorException: Failed to precompile LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043] to /home/mforets/.julia/compiled/v1.2/LazySets/NjrGc.ji.

In [2]:
v = @SVector(rand(2))

LoadError: UndefVarError: @SVector not defined

In [3]:
mA = @SMatrix(rand(2, 8))
polyA = VPolygon([mA[:, i] for i in 1:8])

mB = @SMatrix(rand(2, 8)) .+ 1.5
polyB = VPolygon([mB[:, i] for i in 1:8])

LoadError: UndefVarError: @SMatrix not defined

In [4]:
σ(v, polyA)

UndefVarError: UndefVarError: σ not defined

In [5]:
H = Hyperrectangle(@SVector(rand(2)), @SVector([1.0, 1.0]))

LoadError: UndefVarError: @SVector not defined

In [6]:
σ(v, H)

UndefVarError: UndefVarError: σ not defined

In [7]:
H

UndefVarError: UndefVarError: H not defined

In [8]:
Z = Zonotope(@SVector(rand(2)), @SMatrix(rand(2, 8)))

LoadError: UndefVarError: @SVector not defined

In [9]:
Z.generators

UndefVarError: UndefVarError: Z not defined

In [10]:
@btime σ($v, $Z)

LoadError: UndefVarError: @btime not defined

In [11]:
h1 = Hyperrectangle([0.0, 0.0], [0.5, 1.0])

UndefVarError: UndefVarError: Hyperrectangle not defined

In [30]:
r = HyperRectangle(Vec(0.0, 0.0), Vec(1.0, 2.0))

HyperRectangle{2,Float64}([0.0, 0.0], [1.0, 2.0])

In [13]:
origin(r)

2-element Vec{2,Float64} with indices SOneTo(2):
 0.0
 0.0

In [14]:
widths(r)

2-element Vec{2,Float64} with indices SOneTo(2):
 1.0
 2.0

In [31]:
vertices(r)

([0.0, 0.0], [0.0, 2.0], [1.0, 0.0], [1.0, 2.0])

In [48]:
r = HyperCube(Vec(0.0, 0.0, 0.0), 1.0)

HyperCube{3,Float64}([0.0, 0.0, 0.0], 1.0)

In [49]:
widths(r)

3-element Vec{3,Float64} with indices SOneTo(3):
 1.0
 1.0
 1.0

In [50]:
vertices(r)

([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [0.0, 1.0, 1.0], [1.0, 0.0, 0.0], [1.0, 0.0, 1.0], [1.0, 1.0, 0.0], [1.0, 1.0, 1.0])

In [52]:
x = origin(r)

3-element Vec{3,Float64} with indices SOneTo(3):
 0.0
 0.0
 0.0

In [61]:
using StaticArrays

@SVector(origin(r).data)

LoadError: Use @SVector [a,b,c], @SVector Type[a,b,c] or a comprehension like [f(i) for i = i_min:i_max]

In [22]:
width(r)

1.0

In [19]:
Vec3f0(1.0)

3-element Vec{3,Float32} with indices SOneTo(3):
 1.0
 1.0
 1.0

In [20]:
Float32(1.0)

1.0f0

In [21]:
1.0f0

1.0f0

In [23]:
using Test

In [24]:
x = centered(HyperCube)
@test origin(x) == Vec3f0(-0.5)
@test width(x) == 1.0f0
@test widths(x) == Vec3f0(1.0)
@test maximum(x) == Vec3f0(0.5)
@test minimum(x) == Vec3f0(-0.5)

Test Passed

In [25]:
vertices_list(x)

UndefVarError: UndefVarError: vertices_list not defined

In [26]:
vertices(x)

(Float32[-0.5, -0.5, -0.5], Float32[-0.5, -0.5, 0.5], Float32[-0.5, 0.5, -0.5], Float32[-0.5, 0.5, 0.5], Float32[0.5, -0.5, -0.5], Float32[0.5, -0.5, 0.5], Float32[0.5, 0.5, -0.5], Float32[0.5, 0.5, 0.5])

In [36]:
s = Sphere(Point(0,0,0), 4)

HyperSphere{3,Int64}([0, 0, 0], 4)

In [43]:
t = origin(s)

3-element Point{3,Int64} with indices SOneTo(3):
 0
 0
 0

In [47]:
t.data

(0, 0, 0)

In [40]:
radius(s)

4

In [72]:
using BenchmarkTools

In [78]:
function f(a)
    return reshape([a], 1, 1)
end

function g(a::N) where {N}
    M = Matrix{N}(undef, 1, 1)
    @inbounds M[1, 1] = a
    return M
end

function h(a::N) where {N}
    M = Matrix{N}(undef, 1, 1)
    M[1, 1] = a
    return M
end

function j(a)
    return hcat(a)
end

j (generic function with 1 method)

In [79]:
@btime f(1.0)
@btime g(1.0)
@btime h(1.0)
@btime j(1.0)

  51.547 ns (3 allocations: 192 bytes)
  25.468 ns (1 allocation: 96 bytes)
  25.652 ns (1 allocation: 96 bytes)
  25.650 ns (1 allocation: 96 bytes)


1×1 Array{Float64,2}:
 1.0

In [80]:
hcat(2.0)

1×1 Array{Float64,2}:
 2.0

In [81]:
@which hcat(2.0)

hcat(X::T...) where T<:Number in Base at abstractarray.jl:1280

In [ ]:
julia> c = 1.0f32
1.0f32

julia> [c]
1-element Array{Float32,1}:
 1.0e32

julia> Vc = Vector{typeof(c)}(undef, 1); Vc[1] = c; Vc
1-element Array{Float32,1}:
 1.0e32

julia> @btime [$c]
  28.561 ns (1 allocation: 96 bytes)
1-element Array{Float32,1}:
 1.0e32

julia> @btime (Vc = Vector{typeof($c)}(undef, 1); Vc[1] = $c; Vc)
  30.418 ns (1 allocation: 96 bytes)
1-element Array{Float32,1}:
 1.0e32

In [93]:
function ff(a)
    return [a]
end

function gg(a)
    Vc = Vector{typeof(a)}(undef, 1)
    Vc[1] = a
    return Vc
end

function hh(a)
    return vcat(a)
end

hh (generic function with 1 method)

In [94]:
@btime ff(1.0)
@btime gg(1.0)
@btime hh(1.0)

  23.415 ns (1 allocation: 96 bytes)
  22.813 ns (1 allocation: 96 bytes)
  23.567 ns (1 allocation: 96 bytes)


1-element Array{Float64,1}:
 1.0

In [91]:
c = 1.0

1.0

In [92]:
@btime (Vc = Vector{typeof($c)}(undef, 1); Vc[1] = $c; Vc)

  20.477 ns (1 allocation: 96 bytes)


1-element Array{Float64,1}:
 1.0

In [ ]:
@btime $(Ref(X))[]^2